server:
  port: 8093

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wids?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 5
      max-active: 10
      max-wait: 3000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 实体类和数据库表的字段支持驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # MyBatis日志的实现类
  global-config:
    db-config:
      id-type: auto  # 全局主键策略为自动增长

